### ISSUE TITLE
installation with conda unsuccessful

### ISSUE THREAD

**Issue by sammlapp** [kitzeslab/opensoundscape#257] opened 2021-01-14 20:05 UTC
Creating a conda env and running pip install opensoundscape does not throw an error. However, in the environment, "from opensoundscape.audio import Audio" will give a module not found error. Conda is somehow not building the package or its dependencies correctly. Lauren C had this problem on both Mango (mac) and on her windows machine, and I reproduced it on my mac laptop.

**Comment by sammlapp** [comment] 2021-01-14 22:36
The issue is not conda- specific. Both Lauren's mac and Robin reproduced similar errors with installation (complains that "It seems that scikit-learn has not been built correctly.") using virtualenv instead of conda. On my personal laptop, I got an error with conda but not with virtualenv. Could be python version related, though Lauren still got the error when specifying to conda python 3.7.6.

**Comment by sammlapp** [comment] 2021-01-14 22:44
might be an issue with a specific version of sklearn not working with osx 10.13
https://github.com/scikit-learn/scikit-learn/issues/19063

**Comment by sammlapp** [comment] 2021-01-14 22:51
using scikit-learn==0.22.0 instead of letting it choose (it installs 0.24.0 currently) resolved the issue on robin. Not sure how to specify to poetry certain versions not to use. (The issue will probably be fixed in the next scikit-learn release)

**Comment by sammlapp** [comment] 2021-01-15 20:06
Lauren C's issue was also resolved by using scikitlearn==0.22.0 with python=3.7.6 in conda. (sklearn 0.22.0 is not compatible with python 3.9 though!) So basically just need to change the poetry requirement to not allow the versions that don't work (0.24.0 is known not to work)

**Comment by jkitzes** [comment] 2021-08-05 15:33
I can report that the above bug does not happen for me in a clean environment with scikit-learn==0.24.2 and python==3.8.0 or python==3.7.6. @sammlapp can we presume this was fixed in scikit-learn and we can close?

**Comment by jkitzes** [comment] 2021-08-05 15:35
Also just for the record, I think there were two different issues raised above - not built correctly would definitely be a scikit-learn bug, but module not found should not be caused by an incorrectly built dependency. I had a module not found error that was eventually resolved by making a clean environment with the correct version of Python installed.

**Closed** 2021-12-16 20:30 UTC
