### ISSUE TITLE
BoxedAnnotations.one_hot_clip_labels fails with zero annotations

### ISSUE THREAD

**Issue by sammlapp** [kitzeslab/opensoundscape#599] opened 2022-12-08 23:06 UTC
Underlying error seems to be in `one_hot_labels_on_time_interval` being passed a dataframe without column `start_time`

```
File ~/miniconda3/envs/opso071/lib/python3.9/site-packages/opensoundscape/annotations.py:393, in BoxedAnnotations.one_hot_clip_labels(self, full_duration, clip_duration, clip_overlap, classes, min_label_overlap, min_label_fraction, final_clip)
    386 clip_df = generate_clip_times_df(
    387     full_duration=full_duration,
    388     clip_duration=clip_duration,
    389     clip_overlap=clip_overlap,
    390     final_clip=final_clip,
    391 )
    392 # then create 0/1 labels for each clip and each class
--> 393 return self.one_hot_labels_like(
    394     clip_df=clip_df,
    395     classes=classes,
    396     min_label_overlap=min_label_overlap,
    397     min_label_fraction=min_label_fraction,
    398 )

File ~/miniconda3/envs/opso071/lib/python3.9/site-packages/opensoundscape/annotations.py:321, in BoxedAnnotations.one_hot_labels_like(self, clip_df, classes, min_label_overlap, min_label_fraction, keep_index)
    318 clip_df[classes] = np.nan  # add columns for each class
    320 for (start, end), _ in clip_df.iterrows():
--> 321     clip_df.loc[(start, end), :] = one_hot_labels_on_time_interval(
    322         df,
    323         start_time=start,
    324         end_time=end,
    325         min_label_overlap=min_label_overlap,
    326         min_label_fraction=min_label_fraction,
    327         classes=classes,
    328     )
    330 # re-add the original index, if desired
    331 if keep_index:

File ~/miniconda3/envs/opso071/lib/python3.9/site-packages/opensoundscape/annotations.py:510, in one_hot_labels_on_time_interval(df, classes, start_time, end_time, min_label_overlap, min_label_fraction)
    478 """generate a dictionary of one-hot labels for given time-interval
    479 
    480 Each class is labeled 1 if any annotation overlaps sufficiently with the
   (...)
    504     dictionary of {class:label 0/1} for all classes
    505 """
    507 # calculate amount of overlap of each clip with this time window
    508 df.loc[:, "overlap"] = [
    509     overlap([start_time, end_time], [t0, t1])
--> 510     for t0, t1 in zip(df["start_time"], df["end_time"])
    511 ]
    513 # discard annotations that do not overlap with the time window
    514 df = df[df["overlap"] > 0].reset_index()

File ~/miniconda3/envs/opso071/lib/python3.9/site-packages/pandas/core/frame.py:3805, in DataFrame.__getitem__(self, key)
   3803 if self.columns.nlevels > 1:
   3804     return self._getitem_multilevel(key)
-> 3805 indexer = self.columns.get_loc(key)
   3806 if is_integer(indexer):
   3807     indexer = [indexer]

File ~/miniconda3/envs/opso071/lib/python3.9/site-packages/pandas/core/indexes/base.py:3802, in Index.get_loc(self, key, method, tolerance)
   3800     return self._engine.get_loc(casted_key)
   3801 except KeyError as err:
-> 3802     raise KeyError(key) from err
   3803 except TypeError:
   3804     # If we have a listlike key, _check_indexing_error will raise
   3805     #  InvalidIndexError. Otherwise we fall through and re-raise
   3806     #  the TypeError.
   3807     self._check_indexing_error(key)

KeyError: 'start_time'
```

**Comment by jatinkhilnani** [comment] 2022-12-22 14:52
Duplicate of #548

**Closed by jatinkhilnani** 2022-12-22 14:52 UTC
Labels: annotation
